/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ysl_myjni_Register */

#ifndef _Included_com_ysl_myjni_Register
#define _Included_com_ysl_myjni_Register
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ysl_myjni_Register
 * Method:    helloworld
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_ysl_myjni_Register_helloworld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
